WebXodeTechnologies/nama_taxi

server/.env
server/.gitignore

Mistake in Env - code Changed

---

user/.gitignore
user/app/_layout.tsx

Dev Phase - frontend Started

---

user/app/(routes)/index.tsx
user/app/(routes)/login/index.tsx
user/app/_layout.tsx
user/app/index.tsx
user/screens/onboarding.screen.tsx
user/utils/images/index.tsx

Onboarding Screen Complete

---

user/Themes/app.colors.tsx

Color- button bg change

---

server/.gitignore
server/package-lock.json
server/package.json
server/prisma/schema.prisma
server/tsconfig.json

Backend Intiated with necessary Folder Structure

Backend Intiated with necessary Folder Structure

---

server/app.ts
server/controllers/user.controller.ts
server/routes/user.route.ts

Register user api created

---

user/package-lock.json
user/package.json
user/screens/login/login.screen.tsx

OTP Fetching Error Fix

---

server/controllers/user.controller.ts

backend Code Fix for Api Test - api working fine , need to refactor the changes

backend Code Fix for Api Test

---

user/components/login/phone-number.input.tsx
user/screens/login/login.screen.tsx
user/screens/verification/otp-verification.screen.tsx

Otp Verifcation -testing Completed - frontend complete

Otp Verifcation -testing Completed

---

server/controllers/user.controller.ts
server/routes/user.route.ts

VerifyOtp-controller and Router Logic Complete - backend

VerifyOtp-controller and Router Logic Complete

---

user/app/(routes)/registration/index.tsx
user/components/common/input.tsx
user/components/location/location.search.bar.tsx
user/components/signup/title.view.tsx
user/screens/registration/registration.screen.tsx
user/utils/images/index.tsx

Customer Email Registration screen Complete - frontend with form validation

Customer Email Registration screen Complete

---

user/@types/global.d.ts
user/components/common/button.tsx
user/screens/login/login.screen.tsx
user/screens/verification/otp-verification.screen.tsx

otp verification Process complete -all bugs rectified

otp verification Process complete -all bugs rectified

---

server/package-lock.json
server/package.json

Nodemon for better reloading

---

server/controllers/user.controller.ts

Changes in the Controller Logic

Changes in the Controller Logic

---

server/app.ts
server/controllers/user.controller.ts
server/package-lock.json
server/package.json
server/routes/user.route.ts

verification Complete - backend 
started the email verification Screen and backend logic

verification Complete

---

server/app.ts
server/controllers/user.controller.ts
server/package-lock.json
server/package.json
server/prisma/schema.prisma
server/routes/user.route.ts

Email-verification otp request Module

Email-verification otp request Module

---

user/package-lock.json
user/package.json
user/screens/email-verification/email-verification.screen.tsx
user/screens/verification/otp-verification.screen.tsx

Bug in navigation to home page after email verification

Bug in navigation to home page after email verification

---

server/controllers/user.controller.ts
server/routes/user.route.ts

Verify Email Controller Logic Complete

Verify Email Controller Logic Complete

---

user/screens/email-verification/email-verification.screen.tsx
user/screens/verification/otp-verification.screen.tsx

Email-verification Bug Rectified - frontend

Email-verification Bug Rectified - frontend

---

server/controllers/user.controller.ts

Emailverification Controller Logic Change and bug Rectified - backend

Emailverification Controller Logic Change and bug Rectified

---

user/@types/global.d.ts
user/app/(tabs)/_layout.tsx
user/app/(tabs)/history/index.tsx
user/app/(tabs)/profile/index.tsx
user/app/(tabs)/services/index.tsx
user/app/index.tsx
user/hooks/useGetUserData.tsx
user/screens/registration/registration.screen.tsx

Authentication for user Complete

Authentication for user Complete

---

server/controllers/user.controller.ts
server/middlewares/isAuthenticated.ts
server/routes/user.route.ts

changes in controllers and added Middleware for Auth

changes in controllers and added Middleware for Auth

---

user/app/(routes)/rideplan/index.tsx
user/screens/rideplan/rideplan.screen.tsx

Rideplan Screen Fresh Start

---

user/screens/rideplan/rideplan.screen.tsx

Api Key changed to Hungrybyte

---

user/screens/rideplan/rideplan.screen.tsx

changes in styles

---

user/screens/rideplan/rideplan.screen.tsx

Google Autocomplete Working After changing the api

Google Autocomplete Working After changing the api
